version: "3.5"

services:
  
  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "443:443"      
    networks:
      - mynetwork

  wordpress:
    image: wordpress
    build: ./wordpress
    environment:
      - .env
    depends_on:
      - mariadb
    networks:
      - mynetwork
    
  mariadb:
    image: mariadb
    build: ./mariadb
    ports:
      - "3306:3306"
    environment:
      - .env
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
    driver: bridge