version: "3.5"

services:
 

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "443:443"      
    networks:
      - mynetwork

  wordpress:
    image: wordpress
    build: ./wordpress
    environment:
      - .env
    depends_on:
      - mariadb
    networks:
      - mynetwork
  volumes:
    - type: volume
      target: /home/garance/data

networks:
  mynetwork:
    name: mynetwork
    driver: bridge