version: "3.5"

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

services:  
  nginx:
    image: nginx
    build: ./nginx   
    networks:
      - mynetwork
  
  mariadb:
    image: mariadb
    build: ./mariadb
    volumes:
      - data/mysql:var/lib/mysql
    environment:
      - .env
    restart: always
    networks:
      - mynetwork

  wordpress:
    image: wordpress
    build: ./wordpress
    ports:
      - "8000:80"
    environment:
      - .env
    depends_on:
      - mariadb
    restart: always
    networks:
      - mynetwork
    
